### ISSUE TITLE
ASSETS_DEBUG: True - permission error reading cache file

### ISSUE THREAD

**Issue by louking** [louking/contracts#111]
```
        Message type:       ERROR
        Location:           /var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py:1761
        Module:             app
        Function:           log_exception
        Time:               2019-01-08 16:56:46,027

        Message:

        Exception on / [GET]

Traceback (most recent call last):
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/views/frontend/frontend.py", line 31, in get
    return render_template('index.jinja2')
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/templates/admin/index.jinja2", line 1, in top-level template code
    {% extends "layout.jinja2" %}
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/templates/admin/layout.jinja2", line 60, in top-level template code
    {% assets "admin_css" %}
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/webassets/bundle.py", line 806, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/webassets/bundle.py", line 765, in _urls
    *args, **kwargs)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/webassets/bundle.py", line 609, in _build
    if ctx.updater else True
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/webassets/updater.py", line 173, in needs_rebuild
    super(TimestampUpdater, self).needs_rebuild(bundle, ctx) or \
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/webassets/updater.py", line 103, in needs_rebuild
    return self.check_bundle_definition(bundle, ctx)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/webassets/updater.py", line 93, in check_bundle_definition
    cached_hash = ctx.cache.get(cache_key)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/webassets/cache.py", line 185, in get
    f = open(filename, 'rb')
IOError: [Errno 13] Permission denied: '/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/static/.webassets-cache/b295d7e1656f38f68a0ffdfc8dfe76ec'
```

**Comment by louking** [comment]
httpd configuration file (`contracts.loutilities.com.conf`) needs `WSGIProcessGroup` directive
