### ISSUE TITLE
eventsservicesquery: Invalid cc header

### ISSUE THREAD

**Issue by louking** [louking/contracts#254]
Not sure what user did to cause this

```
        Message type:       ERROR
        Location:           /var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py:1761
        Module:             app
        Function:           log_exception
        Time:               2019-05-06 09:00:28,317

        Message:

        Exception on /eventsservicesquery [POST]

Traceback (most recent call last):
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/views/frontend/eventscalendar.py", line 249, in post
    sendmail( subject, fromlist, tolist, html, ccaddr=cclist )
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/mailer.py", line 77, in sendmail
    sent = gmail.users().messages().send(userId='me', body=message).execute()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 400 when requesting https://www.googleapis.com/gmail/v1/users/me/messages/send?alt=json returned "Invalid cc header">
```

**Comment by louking** [comment]
This should be fixed with 40a3bb2e53c959ca8372cba00aed916578af7356
