### ISSUE TITLE
unicodeencodeerror during logging

### ISSUE THREAD

**Issue by louking** [louking/contracts#278]
```
        Message type:       ERROR
        Location:           /var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/loutilities-0.14.7-py2.7.egg/loutilities/tables.py:462
        Module:             tables
        Function:           wrapped_f
        Time:               2019-06-21 06:02:46,331

        Message:

        Traceback (most recent call last):
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/loutilities-0.14.7-py2.7.egg/loutilities/tables.py", line 445, in wrapped_f
    self.editor_method_posthook(request.form)
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/views/admin/sponsorcontract.py", line 214, in editor_method_posthook
    calculateTrend(sponsordb)
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/trends.py", line 76, in calculateTrend
    thisyeardb.race.race, thisyeardb.raceyear, thisyeardb.client.client, thisyeardb.trend
UnicodeEncodeError: 'ascii' codec can't encode character u'\u012b' in position 3: ordinal not in range(128)
```

**Comment by louking** [comment]
@hhlanglois

**Comment by hhlanglois** [comment]
THrīv Nutraceuticals
