### ISSUE TITLE
eventsservicesquery shows "internal server error" if subject isn't specified

### ISSUE THREAD

**Issue by louking** [louking/contracts#284]
```
        Message type:       ERROR
        Location:           /var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py:1761
        Module:             app
        Function:           log_exception
        Time:               2019-08-08 20:24:39,772

        Message:

        Exception on /eventsservicesquery [POST]

Traceback (most recent call last):
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/views/frontend/eventscalendar.py", line 244, in post
    subject = '[FSRC-RACE-REQUEST] {}'.format(form['subject'])
KeyError: 'subject'

```

**Comment by louking** [comment]
![#284-screen-shot](https://user-images.githubusercontent.com/875138/71972001-cf12c700-31d9-11ea-846d-f11595be752c.png)
