### ISSUE TITLE
Error on first 2020 WDF sponsorship

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#294]
The agreement email actually seems to have been sent, but I received an error.
![Capture](https://user-images.githubusercontent.com/7198600/68582043-c86d0b00-0447-11ea-9baf-6695ff5eefe3.JPG)

The sponsorship is still in the renewed-pending state.

**Comment by louking** [comment]
```
        Message type:       ERROR
        Location:           /var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/loutilities/tables.py:462
        Module:             tables
        Function:           wrapped_f
        Time:               2019-11-11 05:44:31,787

        Message:

        Traceback (most recent call last):
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/loutilities/tables.py", line 445, in wrapped_f
    self.editor_method_posthook(request.form)
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/views/admin/sponsorcontract.py", line 214, in editor_method_posthook
    calculateTrend(sponsordb)
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/trends.py", line 38, in calculateTrend
    prevyeardb = Sponsor.query.filter_by(race_id=race_id, raceyear=thisyear-1, client_id=client_id).one_or_none()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3253, in one_or_none
    "Multiple rows were found for one_or_none()"
MultipleResultsFound: Multiple rows were found for one_or_none()
```

**Comment by louking** [comment]
Issue is multiple sponsorships are being found for prior year, due to in-kind sponsorship and premier sponsorship.
[Sponsorships #294.xlsx](https://github.com/louking/contracts/files/3831178/Sponsorships.294.xlsx)

**Comment by louking** [comment]
You mentioned problems with in kind sponsorships. I see https://github.com/louking/contracts/issues/280 but are there other problems you remember?
