### ISSUE TITLE
coupon date seems to be required

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#298]
I deleted the reference to the coupon date in the benefits table.
But it still showed up in the email body.
So I deleted the variable from the variables list.
And got this error:
Traceback (most recent call last): File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/loutilities/tables.py", line 445, in wrapped_f self.editor_method_posthook(request.form) File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/views/admin/sponsorcontract.py", line 202, in editor_method_posthook mergefields['_coupondate_'] = variables['_coupondate_'] KeyError: '_coupondate_'

**Comment by louking** [comment]
We just have to find the email configuration that refers to _coupondate_, and leave the variable alone as it seems to be required by the code.

I see the email body, adding to the issue so I can look at it later.

```
Thank you so much for your sponsorship of Frederick Women's Distance Festival!

Click to view or download your Sponsorship Agreement for Frederick Women's Distance Festival on August 01, 2020. This agreement contains all your benefits.

For your five (5) complimentary entries, please register using coupon code TC-2020 by July 31.

If you have not already sent us a check, your invoice should arrive soon.
```

original traceback

```
        Message type:       ERROR
        Location:           /var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/loutilities/tables.py:462
        Module:             tables
        Function:           wrapped_f
        Time:               2020-01-06 11:13:38,893

        Message:

        Traceback (most recent call last):
  File "/var/www/www.contracts.loutilities.com/venv/lib/python2.7/site-packages/loutilities/tables.py", line 445, in wrapped_f
    self.editor_method_posthook(request.form)
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/views/admin/sponsorcontract.py", line 202, in editor_method_posthook
    mergefields['_coupondate_'] = variables['_coupondate_']
KeyError: '_coupondate_'
```

**Comment by louking** [comment]
Note the email which is sent that refers to `_coupondate_` is common across races. I don't think this is an issue, though, because all races are following the same protocol
