### ISSUE TITLE
forgot password flow exception

### ISSUE THREAD

**Issue by louking** [louking/contracts#403]
```
        Message type:       ERROR
        Location:           /var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py:1891
        Module:             app
        Function:           log_exception
        Time:               2022-04-27 09:35:08,131

        Message:

        Exception on /account/reset [POST]

Traceback (most recent call last):
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask_security/decorators.py", line 598, in wrapper
    return f(*args, **kwargs)
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask_security/decorators.py", line 420, in decorated
    return fn(*args, **kwargs)
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask_security/views.py", line 476, in forgot_password
    send_reset_password_instructions(form.user)
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask_security/recoverable.py", line 45, in send_reset_password_instructions
    reset_link=reset_link,
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/__init__.py", line 130, in security_send_mail
    sendmail(subject, from_email, recipient, html=html, text=text)
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/loutilities/flask_helpers/mailer.py", line 43, in sendmail
    mail.send(message)
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/var/www/www.contracts.loutilities.com/venv/lib64/python3.6/site-packages/flask_mail.py", line 105, in sanitize_address
    nm, addr = addr
ValueError: too many values to unpack (expected 2)
```

**Comment by louking** [comment]
added configuration for SECURITY_EMAIL_SENDER
