### ISSUE TITLE
python3.9 deploy error: jinja2.exceptions.UndefinedError: '_' is undefined

### ISSUE THREAD

**Issue by louking** [louking/contracts#425]
```
2022-09-29 06:15:04,945 ERROR: Exception on /account/login [GET] [in /var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask_security/decorators.py", line 440, in decorated
    return fn(*args, **kwargs)
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask_security/views.py", line 227, in login
    return _security.render_template(
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask_security/utils.py", line 1062, in default_render_template
    return render_template(*args, **kwargs)
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables-assets/templates/security/login_user.jinja2", line 2, in top-level template code
    {% from "security/_macros.html" import render_field_with_errors, render_field, render_field_errors %}
  File "/var/www/sandbox.contracts.loutilities.com/contracts/contracts/contracts/templates/layout.jinja2", line 1, in top-level template code
    {% extends "layout-base.jinja2" %}
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables-assets/templates/layout-base.jinja2", line 114, in top-level template code
    {% block body %}
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables-assets/templates/security/login_user.jinja2", line 9, in block 'body'
    <h1>{{ _('Login') }}</h1>
  File "/var/www/sandbox.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: '_' is undefined
```

**Comment by louking** [comment]
fixed in d1e2663d1a58aa1f24ad319d96c98632da713c07
