### ISSUE TITLE
eventsservicesquery: allow empty subject

### ISSUE THREAD

**Issue by louking** [louking/contracts#446]
```
        Message type:       ERROR
        Location:           /var/www/www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py:1741
        Module:             app
        Function:           log_exception
        Time:               2023-06-29 18:43:59,131

        Message:

        Exception on /eventsservicesquery [POST]

Traceback (most recent call last):
  File "/var/www/www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/var/www/www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py", line 188, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
  File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/views/frontend/eventscalendar.py", line 244, in post
    subject = '[FSRC-RACE-REQUEST] {}'.format(form['subject'])
KeyError: 'subject'
```

**Comment by louking** [comment]
This could not be reproduced by filling out the form . Possibly a bot does a POST to the address without filling out the form correctly.

![image](https://github.com/louking/contracts/assets/875138/26ce748a-7299-4d14-9384-1c8592a810f8)
