### ISSUE TITLE
socket error when reloading software

### ISSUE THREAD

**Issue by louking** [louking/contracts#451]
```
* Detected change in "C:\\Users\\lking\\Documents\\Lou's Software\\projects\\contracts\\contracts\\contracts\\__init__.py", reloading
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\lking\Documents\Lou's Software\projects\contracts\contracts\venv\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever    super().serve_forever(poll_interval=poll_interval)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\selectors.py", line 324, in select       
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\selectors.py", line 315, in _select      
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

**Comment by louking** [comment]
* https://stackoverflow.com/questions/76442862/oserror-winerror-10038-an-operation-was-attempted-on-something-that-is-not-a
* https://stackoverflow.com/questions/45355301/running-flask-raises-winerror-10038
