### ISSUE TITLE
Resend Contract (on Makin' Hay) throws error

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#461]
Traceback (most recent call last): File "/var/www/www.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py", line 733, in wrapped_f self.editor_method_posthook(request.form) File "/var/www/www.contracts.loutilities.com/contracts/contracts/contracts/views/admin/eventscontract.py", line 216, in editor_method_posthook html = template.render( mergefields ) File "/var/www/www.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render self.environment.handle_exception() File "/var/www/www.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception raise rewrite_traceback_stack(source=source) File "

**Comment by louking** [comment]
```
Message type:       ERROR
        Location:           /var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py:753](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py:753)
        Module:             tables
        Function:           wrapped_f
        Time:               2024-01-30 19:16:25,042

        Message:

        Traceback (most recent call last):
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py)", line 733, in wrapped_f
    self.editor_method_posthook(request.form)
  File "/var/www/[www.contracts.loutilities.com/contracts/contracts/contracts/views/admin/eventscontract.py](http://www.contracts.loutilities.com/contracts/contracts/contracts/views/admin/eventscontract.py)", line 216, in editor_method_posthook
    html = template.render( mergefields )
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/environment.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/environment.py)", line 1301, in render
    self.environment.handle_exception()
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/environment.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/environment.py)", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/environment.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/jinja2/environment.py)", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'client' is undefined
```
