### ISSUE TITLE
raceregistrations exception: AttributeError: 'NoneType' object has no attribute 'couponprovider'

### ISSUE THREAD

**Issue by louking** [louking/contracts#493]
```
Message type:       ERROR
        Location:           /var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py:838](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py:838)
        Module:             app
        Function:           log_exception
        Time:               2024-09-18 20:02:07,422

        Message:

        Exception on /admin/raceregistrations [GET]

Traceback (most recent call last):
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py)", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py)", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py)", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py)", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py)", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py)", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py)", line 1266, in get
    return self._renderpage()
  File "/var/www/[www.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py](http://www.contracts.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py)", line 989, in _renderpage
    self.open()
  File "/var/www/[www.contracts.loutilities.com/contracts/contracts/contracts/views/admin/racessummary.py](http://www.contracts.loutilities.com/contracts/contracts/contracts/views/admin/racessummary.py)", line 93, in open
    if race.couponprovider != 'RunSignUp' or not race.couponproviderid:
AttributeError: 'NoneType' object has no attribute 'couponprovider'
```

**Comment by wardahub-design** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler
